<?xml version="1.0" encoding="UTF-8"?><CoCoMacExport xmlns="http://www.cocomac.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cocomac.org http://www.cocomac.org/cocomac.xsd">
<Header>
<Creator>CoCoMac-Online</Creator>
<CoCoMacVersion>20</CoCoMacVersion>
<ExportDate>2011-04-01T00:39:18+01:00</ExportDate>
<DataType>InterMapRelations_analyzedData</DataType>
<Feedback>
<Query>
<HttpString>Search=CONNECTIVITY&amp;OutputType=XML_BROWSER&amp;SearchString=('8B')[SOURCESITE]OR('8B')[TARGETSITE]&amp;Details=</HttpString>
<SearchString>('8B')[SOURCESITE]OR('8B')[TARGETSITE]</SearchString>
<SqlString>SELECT  Top 32767  ID, ID_SourceSite, SourceSite_A, PDC_Site_A, Hemisphere_A, Density, PDC_Density, Course, ID_TargetSite, TargetSite_B, PDC_Site_B, Hemisphere_B FROM ORT_IntegratedPrimaryProjections WHERE ( ID_SourceSite IN  (SELECT ID FROM BrainMaps_BrainSites WHERE ID_BrainMaps_BrainSiteAcronyms=368))OR( ID_TargetSite IN  (SELECT ID FROM BrainMaps_BrainSites WHERE ID_BrainMaps_BrainSiteAcronyms=368))</SqlString>
</Query>
<Results>165</Results>
</Feedback>
<Comments>CocoMac XML Output</Comments>
</Header>
<ProcessedConnectivityData>
<IntegratedPrimaryProjection>
<SourceSite>
<ID_BrainSite>AAC85-8b</ID_BrainSite>
<SiteType>Area_IsoCtx_2D</SiteType>
<Hemisphere>L</Hemisphere>
<PDC_Site>L</PDC_Site>
<Extent>
<EC>P</EC>
<PDC_EC>L</PDC_EC>
</Extent>
<Laminae>
<Pattern>??????</Pattern>
<PDC_Laminae>-</PDC_Laminae>
</Laminae>
</SourceSite>
<TargetSite>
<ID_BrainSite>AAC85-7a</ID_BrainSite>
<SiteType>Area_IsoCtx_2D</SiteType>
<Hemisphere>L</Hemisphere>
<PDC_Site>A</PDC_Site>
<Extent>
<EC>X</EC>
<PDC_EC>-</PDC_EC>
</Extent>
<Laminae>
<Pattern>??????</Pattern>
<PDC_Laminae>-</PDC_Laminae>
</Laminae>
</TargetSite>
<Density>
<Degree>X</Degree>
<PDC_Density>-</PDC_Density>
</Density>
<Course>I</Course>
</IntegratedPrimaryProjection>
</ProcessedConnectivityData>
<ProcessedConnectivityData>
<IntegratedPrimaryProjection>
<SourceSite>
<ID_BrainSite>ASM94-8b</ID_BrainSite>
<SiteType>Area_IsoCtx_3D</SiteType>
<Hemisphere>L</Hemisphere>
<PDC_Site>A</PDC_Site>
<Extent>
<EC>C</EC>
<PDC_EC>E</PDC_EC>
</Extent>
<Laminae>
<Pattern>??X?XX</Pattern>
<PDC_Laminae>F</PDC_Laminae>
</Laminae>
</SourceSite>
<TargetSite>
<ID_BrainSite>ASM94-24</ID_BrainSite>
<SiteType>Area_IsoCtx_3D</SiteType>
<Hemisphere>L</Hemisphere>
<PDC_Site>C</PDC_Site>
<Extent>
<EC>X</EC>
<PDC_EC>-</PDC_EC>
</Extent>
<Laminae>
<Pattern>??????</Pattern>
<PDC_Laminae>-</PDC_Laminae>
</Laminae>
</TargetSite>
<Density>
<Degree>3</Degree>
<PDC_Density>F</PDC_Density>
</Density>
<Course>I</Course>
</IntegratedPrimaryProjection>
</ProcessedConnectivityData>
</CoCoMacExport>
